<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>

<head>
    <title>Úplné počátky</title>
    <jsp:include page="../menu.jsp"/>
</head>
<body>
<div class="w3-container w3-mobile">
<div class="w3-left-align"><span style="color: #3598db;">Úplné počátky</span></h2>
    <p>Ačkoliv v této době můžeme pouze těžko mluvit o jakékoliv formě českého národa, území, které teď obýváme zůstává po většinu naší psané historie stejné, a tudíž můžeme mluvit o něm. Historie našeho druhu začíná před velmi dlouhou dobou, a to v paleolitu, který trval v období do přibližně 8000 let před naším letopočtem.</p>
<p>Paleolit tvoří nejdelší období dějin, období, kdy byl člověk lovcem a sběračem do značné míry závislým na přírodě a jejích rozmarech. Zároveň jde o etapu, která na činnost člověka uchovala relativně malé množství památek. Pozůstatky lidské činnosti jsou redukovány na kamenné nástroje a odpad z jejich výroby, v mladších obdobích paleolitu nastupují také v omezené míře artefakty kostěné.<br />Počátek dějin člověka je spojen s nástupem čtvrtohor, které se dělí na pleistocén a holocén, jejichž hranici tvoří období cca 8000 př. n. l. Pleistocén je spojen s četnými klimatickými změnami, především několika dobami ledovými-glaciály a meziledovými-interglaciály. Ani v době největšího rozsahu ledovců jimi nebylo naše území podstatněji zasaženo, zalednění se zastavilo v našich severních pohraničních horách.</p>
<p>Během nejstaršího paleolitu, který trval téměř dva miliony let a zahrnuje nejstarší pleistocén, ale částečně i konec třetihor, délkou svého trvání přesahuje celé zbývající lidské dějiny. Tehdy se předchůdci člověka naučili vyrábět kamenné nástroje, začali si zřizovat první jednoduchá obydlí a snad objevili možnosti využití ohně. Z některých zahraničních lokalit máme doloženy uhlíky, předpokládá se, že oheň tedy mohli získat, nikoli zatím ještě rozdělat. Kamenné nástroje, tzv. valounová industrie, se vyráběly jednoduchou technikou. Z valounu se nástroj vytvořil odražením jedné hrany, popřípadě obou. Složitějším odštěpováním se dospělo až k primitivním formám pěstního klínu. V nejstarším paleolitu vytvořeny základy pro další rozvoj člověka, jako například úspěšný lov, výroba kamenných nástrojů a zejména předávání nahromaděných dovedností dalším generacím, které předpokládá alespoň základní společenské formy, jako rodina nebo základy řeči.</p>
<p>Na nejstarší paleolit navazuje takzvaný starý paleolit, který pokrývá převážnou část středního pleistocénu a končí přibližně s nástupem předposlední doby ledové. Člověk se na našem území vyskytoval ve větším počtu, a definitivně se prosadila jeho větev vedoucí k dnešnímu člověku, ve starém paleolitu člověk vzpřímený. Tento člověk přežil několik klimatických a na ně navázaných změn, byl tedy dostatečně přizpůsobivý. Dokázal ulovit téměř všechna zvířata, jak velká, tak drobná, ale i značně plachá, což svědčí o tom, že uměl lovit v kolektivu a byl schopen komunikovat s ostatními. Úspěšný lov předpokládal dokonalé nástroje, kterými byly ve starém paleolitu pěstní klíny, které byly univerzálním nástrojem. Velká úloha připadala také pomůckám z organických materiálů, ze kterých se vyráběly oštěpy, palice nebo kyje. Ty se však nedochovaly. Staropaleolitický člověk neobýval stálá sídla, i když je pravděpodobné, že preferoval místa, kde snadněji získával obživu. Na jednotlivých stanovištích také přímo vyráběl kamenné nástroje. Někdy se soudí, že produkty úštěpové techniky zanechával na místě, u výrobně mnohem náročnějších pěstních klínů ale tuto jistotu nemáme. Bezpečně je dokázáno používání ohně, ale není známo, zda byl tehdejší člověk schopen jej i rozdělat. Bydlel v jednoduchých přístřešcích. Homo erectus žil pravděpodobně v menších tlupách, nejspíše větších rodinách, pohybujících se po velkých územích. Nálezy z Čech dokládají oblibu tábořišť na březích toků či vodních ploch, ale na trasách, po nichž se pohyboval, si také vybíral místa s výskytem surovin vhodných pro výrobu kamenných nástrojů. V rozvoji abstraktního myšlení postoupil člověk starého paleolitu natolik, že registrujeme prvé, nevýrazné stopy umělecké činnosti jako ryté čáry na kostech, používání barviv a jiné. Vyloučeny nejsou ani určité rituální praktiky.</p>
</div>
</div></body>
</html>